version: '3'
services:
        app:
                image: gdx2-app:latest
                build: ./docker
                container_name: gdx2-app
                volumes:
                        - ./:/opt/
 
